### ISSUE TITLE
Notifications sometimes do not appear on Windows

### ISSUE THREAD

**Issue by phts** [phts/firefox-owa-notifications#1]
This happens due to [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1337490) in case when we have created several notification with different data at the same time (e.g. email and calendar events). 

If we have only one type (e.g. only email) then such notification is showing correctly.

Playground: https://girliemac.com/html5-notifications-webOS-style/

**Comment by PhilippBaranovskiy** [comment]
A good idea may be to group notifications into one, how do you think?
