### ISSUE TITLE
Do not show a notification for drafts

### ISSUE THREAD

**Issue by mardukbp** [phts/firefox-owa-notifications#7]
When composing an email, this Firefox extension generates a notification every time the draft is saved by OWA. This is not only annoying, it also can sometimes freeze the tab.

**Update**: @phts Please add `Entwürfe` (German for Drafts) to the list of ignored folders. Thank you!

**Comment by phts** [comment]
@mardukbp 

Could you please provide translations for all those folders:

* Drafts
* Junk Email
* Deleted Items

I will add them to the extension as well

**Comment by phts** [comment]
No worries, already found.

**Comment by mardukbp** [comment]
Thank you @phts!
